server:
  port: 8060

spring:
  ai:
    mcp:
      server:
        name: stock-mcp-server
        version: 1.0.0

logging:
  level:
    root: INFO
    com.agilesolutions.mcp: DEBUG
    org.springframework.ai: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

twelvedata:
  api:
    url: https://api.twelvedata.com/
    key: demo